### PR TITLE
Feature 2 is complete and works

### PR DESCRIPTION
**Pull request by lclittle**

### CODE REVIEW

**Comment by kgbullard** [comment]
The code works well.

**Review by czlanier — COMMENTED** [review]
Could have made string[] tweets MAX int private variable

**Review by czlanier — APPROVED** [review]
Code runs well!

**Review by kgbullard — APPROVED** [review]
Just Remove the block code you are no longer using, instead of commenting it out. It'll be easier to read.

**Review by ccannon94 — APPROVED** [review]
:+1:

**Pull request merged**
